### ISSUE TITLE
Status??

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#46] opened 2019-11-14 10:05 UTC
What is the status with this template? 

I don't see any attempt to look at any of the accessibility issues.

Because of all the markup changes here it's not possible for this to be an alternative template. It can only be a replacement template.

There are some great improvements in this template and some that are not. 

Surely the best way forward is to look at what ideas can be taken from this template and added to **atum**. Otherwise at the pace of change here we won't be remotely ready to consider it for joomla 4 until the summer :(

/cc @wilsonge @HLeithner

**Comment by micker** [comment] 2019-11-14 10:29
for me its a good idea to add some feature in atum
- systeme to create menu with dropdown (just need a search input)
- drag and drop panel in dashboard
- some part of UX in article editing (image zone + tab arrangement + tiny editor
- mobile menu
- color of sidemenu (in atumn blue color is to high then content zone (we can update css to have a better link less "hard")

**Comment by kawshar** [comment] 2019-11-15 09:10
Hi Brian
The team is struggling with some issues regarding CI integration. The team is asking for a guideline to all possible channels but no one care to answer. However, team is trying to solve the issue and as soon as the issue is resolved, the latest developments will be submitted as PR.

Thanks

**Comment by brianteeman** [comment] 2019-11-15 09:44
I thought @marcodings was doing all of that for ou

**Comment by kawshar** [comment] 2019-11-15 09:55
He is doing his best but he is not an expert on everything. If you got a minute then you are cordially requested to help https://github.com/joomla-projects/j4adminui/pull/41

**Comment by brianteeman** [comment] 2019-11-15 10:52
Help with what? If you mean the failed tests then I can't really help on that but I don't know why you are even touching the installation folder in the first place. Surely that is out of scope

**Comment by kawshar** [comment] 2019-11-15 12:15
That's why the progress is stopped. We touched the installation in order to provide a seamless design experience over the whole Joomla. However, I hope issue will be resolved within a very short time and the development process will be accelerated after that.

Thanks

**Comment by brianteeman** [comment] 2019-11-15 12:34
A great example of why you have separate pull requests for separate issues

**Comment by kawshar** [comment] 2019-11-15 13:42
I did not get your last comment. Btw, you are not showing anyway. If you believe we are going in the wrong direction, tell us the right direction. Or, we will never learn.

Thanks

**Comment by marcodings** [comment] 2019-11-15 14:39
> I thought @marcodings was doing all of that for ou

I'm liaising and facilitating, parts were/are beyond my expertise and parts i had no privileges. 
Long story short to date there were a number of unforeseen complications with continuous integration and we do not want to cut corners. 

Challenges are revolving/interlocked around 3 different repo's and we seem to be close to wrapping them up. With that out of the way we can have a baseline for making changes in more controlled way and start addressing the "functional" issues such as the accessibility.

Decision to date by production is to treat "Khonsu" (yes we are changing the name to represent an Egyptian god) as a potential alternative template as set forth in the Readme.md for the j4adminui project. Insights may change with substantiated "evidence" but we are not there yet.

I'm sure there will be "functional" cross-pollination between "Atum" and "Khonsu", at the moment visually they seem to appeal to different community groups/ fan-bases.

Biggest hurdle ATM is to get J!4 to beta asap, so any potentially BC breaking changes are in. Production is not waiting for "Khonsu", what we can do after beta (cross pollination and such) and how we get tot RC.. the future will tell.

**Comment by brianteeman** [comment] 2019-11-15 15:16
The current implementation of this template has been designed in such a way that it cannot be an alternative template. Until that is addressed anything else is a waste of time

**Comment by brianteeman** [comment] 2019-11-15 15:18
> If you believe we are going in the wrong direction, tell us the right direction. Or, we will never learn.

The current code can not be used as an alternate template as it changes so much that it breaks the existing template and is not what you proposed it would be before this process began.

My personal opinion is that there are **some** really good ideas here and that just like any other contribution to joomla they should be made as individual discreet pull requests to the core.

**Comment by marcodings** [comment] 2019-11-15 15:55
Unless we can get specific about actionable items or arguments there is no point in discussing generic opinions. This is similar to https://github.com/joomla-projects/j4adminui/issues/44

**Closed as completed by marcodings** 2019-11-15 15:55 UTC

**Comment by brianteeman** [comment] 2019-11-15 16:03
@marcodings I provided a specific list of actionable items. As you don't appear to be able to find it here is the link https://github.com/joomla-projects/j4adminui/issues/11 that was created three weeks ago

Keeping closing valid issues doesn't hide the problem

**Comment by astridx** [comment] 2019-11-15 17:20
@marcodings I think Brian is right with "Keeping closing valid issues doesn't hide the problem"

At first glance, I like this temple much better than the current one. It is much more intuitive for me. But I know that a template can never be right or wrong. It depends on the Individuum.

I thought it was very good that the template is supposed to be created publicly. But then I was surprised that none of the many people who found everything great on Facebook participated here. And I myself thought about doing a PR. I was not sure if this was wanted here. Nobody else has done a PR so far.

I believe that an alternative to the current (for some not nice and intuitive) template is very good. At the moment it is not an alternative, because the current Atum template is not compatible with this template. Maybe we should focus less on fulfilling all requirements (I would install this template as an alternative. I do not need a11y)

Perhaps it is more important to achieve that both templates can work together.
